- name: Install CoreDNS add-on
  shell: "kubectl apply -f roles/addons/templates/coredns.yml"

- name: Store Dashboard certificate in a secret
  shell: "kubectl create secret generic kubernetes-dashboard-certs --from-file={{ PKI_DIR }}/k8s-dashboard.bundle -n kube-system"
  register: create_secret
  failed_when: "'already exists' not in create_secret.stderr"
  ignore_errors: True

- name: Install Dashboard
  shell: "kubectl apply -f roles/addons/templates/kubernetes-dashboard.yml"

- name: Granting admin privileges to Dashboard's Service Account
  shell: "kubectl apply -f roles/addons/templates/dashboard-admin.yml"
